### ISSUE TITLE
mapbox geobuf

### ISSUE THREAD

**Issue by gertcuykens** [murphy214/geobuf_new#1]
I think they are close enough to maybe use the same proto format?

https://github.com/mapbox/geobuf/blob/master/geobuf.proto

**Comment by murphy214** [comment]
The deviations from there spec exist for a few reasons. Probably stemming from different use cases. The main use case I've made underlying changes to there proto spec file for is stream processing, with MapBox's geobuf you have to the entire file before you can do any feature processing my changes allow one you to operate on one feature at a time.

Probably I use geobuf for some time of stuff they use line-delimitted geojson for if I had to guess. However I should probably change the name to eliminate future confusion with MapBox's spec but it is the same underlying concept a geojson interchange format, in protobuf form.

**Comment by gertcuykens** [comment]
Ok thanks ps don't think you need to change the name. Streaming is a valid argument, maybe it should be the other way around and the mapbox spec should change so it's a more stream friendly spec. Maybe if you have time at a change proposal to the mapbox spec
