### ISSUE TITLE
javascript geobuf library and this geobuf are not compatible. (I am Korean, so do not speak English well....)

### ISSUE THREAD

**Issue by kwunjaehyun** [murphy214/geobuf_new#4]
Hello!

Thank you for your library.

I'm trying to encode with your library and decode with javascript geobuf (https://github.com/mapbox/geobuf).

but empty object returned.

Is it different format?

I encode gebuf this code. (golang)->  geobuf.ConvertGeojson(geojsonfilepath, pbffilepath)

I decode gebuf this code (javascript) -> var bf = geobuf.decode(new Pbf(data);

console.log(bf) -> {}

**Comment by murphy214** [comment]
Hi yes this is a different version from the Mapbox version. I apologize for any inconvenience, perhaps I should be more explicit in the readme. Which is described briefly in the readme. 

However you wanted to use this protospec client side you could right your own parsing implementation using MapBox's [pdf](https://github.com/mapbox/pbf) parsing library and look at some of my code [here](https://github.com/murphy214/pbf/blob/master/pbf.go#L511)

**Comment by kwunjaehyun** [comment]
Thank you very much.
